### ISSUE TITLE
Mossnet script needs to be added after every deployment/down/up

### ISSUE THREAD

**Issue by umar221b** [autolab/docker#54]
The mossnet script should be added inside a `vendor` directory that is not persisted, which means it needs to be copied after every deployment or compose down/up. I do not think it is a good idea to persist the `vendor` directory, and I am unable to persist the script alone because when the Autolab instance is first setup the `mossnet` script does not exist and docker will instead create a directory called `./vendor/mossnet`.

Possible solutions:

- Add `vendor` to `autolab`'s volumes in `docker-compose.yml`.
- Move `mossnet` to some other directory, add the script and directory to the autolab repository, and persist it in `autolab`'s volumes in `docker-compose.yml`.

**Comment by damianhxy** [comment]
Hi @umar221b,

I'm afraid I don't quite understand your request / suggestions here.

1. Currently, the vendor directory isn't persisted, but your suggestion of adding it as a volume would persist it, which doesn't seem to be what you want -- am I misunderstanding something?
2. Why is it not a good idea to persist the vendor directory? AFAIK, it is used solely to store `mossnet`.
3. Even if the vendor directory is not persisted (like now), I do not think that means it needs to be copied after every deployment or compose down/up -- docker should keep track of local modifications made.

**Comment by umar221b** [comment]
My request is to find a way to persist the `mossnet` script in the container.

1. Sorry if I did not make it clear. Please forget about the first suggestion. See below.
2. I do not think that is a good idea because the `vendor` directory could contain other 3rd party assets. I have done more research and my understanding is as follow:
    1. In general, the first time a container is built from the image, vendor assets (if any) will be added to the vendor directory on the container.
    3. Docker spins the container up, and if vendor is added as a volume, docker will load the host's vendor directory on top of the container's vendor directory. The host's vendor directory only contains the `mossnet` script so all the other vendor assets are lost.
3. I copied the script to the container and ran `compose down/up` and it was removed. I might have modified the compose configuration which could have caused the removal, but I feel it should be explicitly persisted because the script acts more like a configuration file that is always needed even if the container is rebuilt.

Hope that makes sense.

**Comment by umar221b** [comment]
>I copied the script to the container and ran compose down/up and it was removed. I might have modified the compose configuration which could have caused the removal, but I feel it should be explicitly persisted because the script acts more like a configuration file that is always needed even if the container is rebuilt.

I retested this. If you create the directory inside the container and then down and up it will be removed. Which makes sense because it is not persisted in a volume. My suggestion is to move it somewhere else (for the above reasons) and persist it.

**Comment by damianhxy** [comment]
> ...  the vendor directory could contain other 3rd party assets
> ... vendor assets (if any) will be added to the vendor directory on the container

By 3rd party assets, are you planning to add your own assets to `vendor/assets`? AFAIK, Autolab doesn't make use of the `vendor` directory other than for `mossnet`, and nothing else writes to it, so there wouldn't be an issue with overwriting the directory (if we mount it as a volume).

> If you create the directory inside the container and then down and up it will be removed

I've tested this as well, and it still appears to me that data is persisted. Perhaps there is some kind of configuration difference (see pictures at the end).

**My suggestion**

Moving `mossnet` to a different directory would be a breaking change that I would like to avoid.

The least breaking change I can think of is to update the Autolab repository to include a dummy `vendor/mossnet` file, and add the volume mapping. This would overwrite the existing `mossnet` file (if any) stored inside the container, but it should not be a big deal since it is relatively easy to set up `mossnet` again.

Let me know what you think.

--------

**Original:**
<img width="1270" alt="Screenshot 2023-03-30 at 16 35 32" src="https://user-images.githubusercontent.com/9074856/228958387-c4435541-0f7a-4f9f-90ac-903139f1e358.png">

**After `mkdir vendor; cd vendor; touch mossnet`**
<img width="1270" alt="Screenshot 2023-03-30 at 16 35 55" src="https://user-images.githubusercontent.com/9074856/228958490-be09d497-6c9a-4855-bac9-3abd695f0ce4.png">

**After restarting container**
<img width="1270" alt="Screenshot 2023-03-30 at 16 36 30" src="https://user-images.githubusercontent.com/9074856/228958474-df7a2859-4b72-40e5-a319-56f242957d4a.png">

**Comment by umar221b** [comment]
>By 3rd party assets, are you planning to add your own assets to vendor/assets? AFAIK, Autolab doesn't make use of the vendor directory other than for mossnet, and nothing else writes to it, so there wouldn't be an issue with overwriting the directory (if we mount it as a volume).

I am not planning to add any at the moment, but I was speaking in general - in case a library that uses the vendor folder was added in the future, just so it would not break.

>I've tested this as well, and it still appears to me that data is persisted. Perhaps there is some kind of configuration difference (see pictures at the end).

I see what is going on here. I was running `docker compose down` which stops the container and **destroys** it. Stopping it per se should not remove the non-persisted data (which what restart does, stop then start). Which still makes this a problem.

If you are not comfortable with a breaking change I think we could just leave things as is because I believe persisting vendor might come back to bite the developers in the future. If you agree we can close the issue.

**Comment by damianhxy** [comment]
> I am not planning to add any at the moment, but I was speaking in general - in case a library that uses the vendor folder was added in the future, just so it would not break.

I see -- that makes sense.

> If you are not comfortable with a breaking change I think we could just leave things as is because I believe persisting vendor might come back to bite the developers in the future. If you agree we can close the issue.

Indeed, it was a oversight on our part not to persist `mossnet`, but adding the mapping now would break existing installations, without much benefit.

I would recommend either adding the volume mapping for your own installation, or using `docker compose stop` instead of `docker compose down`. That should avoid wiping the `vendor` folder.

I will be closing this issue as a wontfix, but feel free to follow up if any further issues arise!
